#!/bin/csh -f
cd "/home1/hci/user/allenl/Iclab 2026 spring/final project/Final_Project/00_TESTBED"
vcs -timescale=1ns/1fs -j8 -sverilog +v2k -full64 -Mupdate -R -debug_access+all -y /usr/cad/synopsys/synthesis/cur/dw/sim_ver/ +libext+.v -f filelist.f +incdir+../01_RTL +define+RTL +define+RUN +define+PERF +notimingchecks -o simv -l /home1/hci/user/allenl/vcs_rtl.log
